const contactMessage =
  'กรุณาติดต่อ BLS Customer Service 0-2618-1111 หรือ <a href="mailto:customerservice.bualuang.co.th">customerservice.bualuang.co.th</a>';
const pleaseContactMessage = `หากมีข้อสงสัย ${contactMessage}`;

const defaultDisplayValues = {
  customerNo: "",
  gender: "",
  titleTh: "",
  nameTh: "",
  surnameTh: "",
  nameEn: "",
  surnameEn: "",
  mobileNo: "",
  email: "",
  nationality: "",
  birthday: "",
  age: "",
  cardType: "",
  cardID: "",
  oldAddress: "",
  openDate: "",
  fundAccountNo: ""
};

const defaultFormData = {
  flagNotExpire: "0",
  expireDate: "",
  issueCountry: "000",
  flagMartialStatus: "1",
  spouseNameTh: "",
  spouseSurnameTh: "",
  spouseNameEn: "",
  spouseSurnameEn: "",

  contactAddress: defaultAddressFormData,
  flagRegisAdrs: "1",
  registerAddress: defaultAddressFormData,
  officeAddress: defaultAddressFormData,
  officeCompanyName: "",
  occupation: "",
  occupationOth: "",
  businessType: "",
  businessTypeOth: "",
  srcIncomeCountry: "000",
  srcIncomeCountryOth: "",
  srcIncome: [],
  srcIncomeOth: "",
  monthlyIncome: "",
  position: "",
  flagPoliticalPerson: "0",
  politicalPosition: "",
  assetValue: "",
  flagIsUSCitizen: "0",
  flagHolderUSResidentCard: "0",
  flagUSResidentForTax: "0",

  flagMailingAdrs: "1",

  investmentObjective: [],
  investmentObjectiveOth: "",
  flagAts: "0",
  atsBank: "",
  atsBranch: "",
  atsAccountType: "",
  atsAccountName: "",
  atsAccount: "",
  flagDiv: "0",
  divBank: "",
  divBranch: "",
  divAccountType: "",
  divAccountName: "",
  divAccount: "",

  suitability: null
};

const defaultAddressFormData = {
  addressNo: "",
  moo: "",
  village: "",
  floor: "",
  soi: "",
  road: "",
  province: "",
  district: "",
  subdistrict: "",
  zipcode: "",
  country: "000"
};

const defaultSubmitFormData = {
  expireDate: "",
  issueCountry: "",
  flagMartialStatus: "",
  spouseNameTh: "",
  spouseSurnameTh: "",
  spouseNameEn: "",
  spouseSurnameEn: "",
  contactAddress: defaultAddressFormData,
  flagRegisAdrs: "",
  registerAddress: defaultAddressFormData,
  officeAddress: defaultAddressFormData,
  officeCompanyName: "",
  occupation: "",
  occupationOth: "",
  businessType: "",
  businessTypeOth: "",
  srcIncomeCountry: "000",
  srcIncomeCountryOth: "",
  srcIncome: [],
  srcIncomeOth: "",
  monthlyIncome: "",
  position: "",
  flagPoliticalPerson: "",
  politicalPosition: "",
  assetValue: "",
  flagIsUSCitizen: "",
  flagHolderUSResidentCard: "",
  flagUSResidentForTax: "",
  flagMailingAdrs: "",
  investmentObjective: [],
  investmentObjectiveOth: "",
  atsBank: "",
  atsBranch: "",
  atsAccountType: "",
  atsAccountName: "",
  atsAccount: "",
  divBank: "",
  divBranch: "",
  divAccountType: "",
  divAccountName: "",
  divAccount: "",
  suitability: [],
  score: "",
  grade: "",
  qnversion: "",
  fatcaflag:"",
  fatca:[],
  taxpayertype:"",
  taxpayerid:"",
  crsflag:"",
  crs_detail:[],
  pob:"",
  pobcity:"",

};

export {
  contactMessage,
  pleaseContactMessage,
  // unemployedCodeList,
  defaultDisplayValues,
  defaultAddressFormData,
  defaultFormData,
  defaultSubmitFormData
};
